spring.application.name=demo

spring.config.import="nacos:${spring.application.name}"

spring.cloud.nacos.config.server-addr=http://121.4.119.252:8848
spring.cloud.nacos.config.namespace=0fa81b7f-a989-4311-a60e-3ee0834b0ef3
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=yml


